---
# Install macos-packages packages

- name: unwanted packages are removed
  package:
    name: "{{ macos-packages_packages_remove }}"
    state: absent
  become: true
  when: macos-packages_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ macos-packages_packages_repos }}"
    state: "{{ macos-packages_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ macos-packages_packages_prereq }}"
    state: "{{ macos-packages_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ macos-packages_packages_install }}"
    state: "{{ macos-packages_packages_state }}"
  become: true
